### ISSUE TITLE
Nice to have: picture frame screensaver

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/things-controller#10]
_See also [this issue at the gateway](https://github.com/mozilla-iot/gateway/issues/1506)._

Nowadays a lot of people have old or cheap tablets (of phones). They will likely often be used as permanent remote controls and data displays for the Mozilla Gateway.

Some of these may be mounted to walls, some have cases that allow them to be propped up on a cabinet, others may simply find a home in the living room.

Currently, these tablets may permanently show the interface so that people can see things like temperature, weather forecast, etc at a glance, or toggle actuators.

However, users may prefer to hide the interface most of the time, and have the tablet function as a picture frame until it is tapped/moved.

PRACTICAL

The user can choose to enable "picture frame screensaver" from settings. Optionally, there is also a 'wait X minutes before going into screensaver mode" slider here.
The gateway reveals a 1Gb SMB drive that shows up in the users network.
If users place pictures on that drive they will be used for the picture frame screensaver. Other files than pictures are ignored/deleted.
If the user has selected the picture frame option, and the web interface has not been interacted with for X amount of minutes, then the slideshow starts.
If the user touches the screen, the slideshow stops.
If the user has created an automation that requires something being shown on the screen, then the slideshow stops.
OPTIONAL

Create a "go fullscreen" (and close fullscreen) button in the interface, so that the UX is shown full screen. This is a feature that would still be useful even if the picture frame feature is not implemented. At the start of the photo display the browser could go fullscreen. If the browser was originally not in fullscreen mode, the browser could disable fullscreen mode when the slideshow is stopped by a touch event.
Allow videos to be uploaded as well.
Create more settings, like "show in black and white", "use ken burns effect", "show videos in slow motion".
ALTERNATIVE

A SMB drive is not created, but a web-based photo upload is used instead.
ADVANTAGES

Increased privacy: data from the system is not immediately visible to visitors of the home.
Security by obscurity: visitors do not immediately see that he tablet is a control surface.
Technically relatively easy to implement.
A popular feature that is still rarely implemented.
OPPORTUNITIES

If the gateway has an internet connection, then it could show pictures from online photography resources.

**Comment by mrstegeman** [comment]
How about this as an option: https://github.com/mrstegeman/photo-cycler-webthing

Add that as a web thing and open the external UI. Picture frame done!

**Comment by flatsiedatsie** [comment]
Interesting! Could you explain a bit more how it works and how to install it? Then I'll give it a go!

**Comment by mrstegeman** [comment]
1. Clone that git repo to some computer on your network.
2. Drop some pictures (.jpg) in the `photos` directory.
3. `cd` into either `python`, `node`, `rust`, or `java`, then `./run.sh`.
4. Ensure that `thing-url-adapter`, aka the "Web Thing" add-on, is installed on your gateway.
5. Click + on the things screen on your gateway's UI.
6. If your "Photo Cycler" thing shows up, add it. If not, you can click "Add by URL" and follow the prompts. You'll use something like `http://<hostname>.local:8888/`.
7. After adding your new thing, a little link icon will show up at the top left of its icon on your Things screen. Clicking that will yield a "picture frame", essentially.

**Comment by flatsiedatsie** [comment]
Thanks, I'll try it!

I already have the [MySController-rs](https://github.com/tsathishkumar/MySController-rs/issues) software running a webthing on that port. Does that matter?

**Comment by mrstegeman** [comment]
You'll need to change the port in one of them.

**Comment by flatsiedatsie** [comment]
Got an error on the first run. Ran it again as sudo and it was fixed.

```
pi@gateway:~/photo-cycler-webthing/python $ ./run.sh
Collecting webthing>=0.11.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/03/7e/c8f362a6e7b5d77c1fd0209e688e66ec393d39acc4f38b46bace7d053b42/webthing-0.11.0-py3-none-any.whl
Collecting tornado (from webthing>=0.11.0->-r requirements.txt (line 1))
  Downloading https://www.piwheels.org/simple/tornado/tornado-5.1.1-cp35-cp35m-linux_armv7l.whl (462kB)
    100% |████████████████████████████████| 471kB 362kB/s 
Collecting jsonschema (from webthing>=0.11.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting pyee (from webthing>=0.11.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/8e/06/10c18578e2d8b9cf9902f424f86d433c647ca55e82293100f53e6c0afab4/pyee-5.0.0-py2.py3-none-any.whl
Collecting zeroconf (from webthing>=0.11.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/d2/4e/3e751bc1f33d0368bdba509a140cb9f2e54cd1cfb8ebcf4ebd8a5eef794b/zeroconf-0.21.3-py2.py3-none-any.whl
Collecting netifaces (from webthing>=0.11.0->-r requirements.txt (line 1))
  Downloading https://www.piwheels.org/simple/netifaces/netifaces-0.10.9-cp35-cp35m-linux_armv7l.whl
Collecting ifaddr (from zeroconf->webthing>=0.11.0->-r requirements.txt (line 1))
  Downloading https://www.piwheels.org/simple/ifaddr/ifaddr-0.1.6-py3-none-any.whl
Installing collected packages: tornado, jsonschema, pyee, ifaddr, zeroconf, netifaces, webthing
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/lib/python3.5/distutils/command/install.py", line 273, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
Traceback (most recent call last):
  File "photo-cycler-webthing.py", line 3, in <module>
    from webthing import SingleThing, Property, Thing, Value, WebThingServer
ImportError: No module named 'webthing'

```

**Comment by flatsiedatsie** [comment]
I have three JPG's in the folder, but there seems to be a 404 error.

![picture_frame](https://user-images.githubusercontent.com/805405/51351463-d873c280-1aa2-11e9-96fc-953e0c104402.png)

WARNING:tornado.access:404 GET /static/current.jpg (192.168.2.38) 4.95ms
WARNING:tornado.access:404 GET /favicon.ico (192.168.2.38) 5.43ms
WARNING:tornado.access:404 GET /static/current.jpg (192.168.2.38) 12.89ms
WARNING:tornado.access:404 GET /static/current.jpg (192.168.2.38) 6.63ms
WARNING:tornado.access:404 GET /static/current.jpg (192.168.2.38) 6.23ms
WARNING:tornado.access:404 GET /static/current.jpg (192.168.2.38) 3.91ms

**Comment by mrstegeman** [comment]
I just fixed this in the gateway a few minutes ago. Things should work better when 0.7 is released next week.

**Comment by mrstegeman** [comment]
As for the python error above, there's a silly issue with `pip` on the Raspberry Pi. Let me try to fix that in the `run.sh` script.

**Comment by mrstegeman** [comment]
The `run.sh` script should be fixed now.

**Comment by mrstegeman** [comment]
Can you do the following:
```bash
ls -l ~/photo-cycler-webthing/photos
ls -l ~/photo-cycler-webthing/static
```

**Comment by flatsiedatsie** [comment]
It's working now! Very nice!

This may be a very useful case to explore how add-ons/plugins/apps could be integrated and have enough control to do interesting things. There are some open questions like:
- Right now this opens the photo viewer in a new window. It would be great if add-ons could open up in some kind of overlay on top of the interface? 
- Could they go fullscreen?
- Could this 'plugin' start after a certain amount of in activity?
- Could an "click to upload your photos" feature be added somehow? This means the plugin/app would need to have hook into a 'take-over display' option, as well as a 'create a settings page' option.

**Comment by mrstegeman** [comment]
Glad it's working! This is an external web thing which lives completely outside of the gateway, so it couldn't really do the things you're suggesting. However, we do have the concept of "extension" add-ons which can extend the UI and such. We plan to develop this soon. Could you add some of your ideas to that issue?

https://github.com/mozilla-iot/gateway/issues/1505

**Comment by flatsiedatsie** [comment]
I'd be happy to. I've already done quite a bit on this, even creating some mockups.
